version: '3'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_db:/data
      
  api:
    command: npm start
    build: .
    ports:
      - 80:8080
    depends_on:
      - mongo
    environment:
      - PORT=8080

volumes:
  mongo_db:
